/**
 * Role-Based Access Control (RBAC) & Permission Engine.
 *
 * Maps granular resource permissions to tenant workspace roles.
 * Built-in roles:
 * - Owner: complete authority over workspace, settings, billing, deletion
 * - Admin: complete operational authority, member management, integrations, agent configuration
 * - Manager: team supervision, approval workflows, campaigns, CRM management
 * - Agent / Member: operational CRM access, conversations, tasks, appointments
 * - Viewer: read-only access
 */

export const ROLES = {
  OWNER: "owner",
  ADMIN: "admin",
  MANAGER: "manager",
  AGENT: "agent",
  MEMBER: "member",
  VIEWER: "viewer",
};

export const PERMISSIONS = {
  // CRM Contacts
  CONTACTS_READ: "contacts.read",
  CONTACTS_CREATE: "contacts.create",
  CONTACTS_UPDATE: "contacts.update",
  CONTACTS_DELETE: "contacts.delete",

  // CRM Companies
  COMPANIES_READ: "companies.read",
  COMPANIES_CREATE: "companies.create",
  COMPANIES_UPDATE: "companies.update",
  COMPANIES_DELETE: "companies.delete",

  // CRM Deals
  DEALS_READ: "deals.read",
  DEALS_CREATE: "deals.create",
  DEALS_UPDATE: "deals.update",
  DEALS_DELETE: "deals.delete",

  // CRM Tasks
  TASKS_READ: "tasks.read",
  TASKS_CREATE: "tasks.create",
  TASKS_UPDATE: "tasks.update",
  TASKS_DELETE: "tasks.delete",

  // Inbox & Messaging
  CONVERSATIONS_READ: "conversations.read",
  CONVERSATIONS_REPLY: "conversations.reply",
  CONVERSATIONS_ASSIGN: "conversations.assign",
  CONVERSATIONS_CLOSE: "conversations.close",
  MESSAGES_SEND: "messages.send",

  // Appointments
  APPOINTMENTS_READ: "appointments.read",
  APPOINTMENTS_CREATE: "appointments.create",
  APPOINTMENTS_UPDATE: "appointments.update",
  APPOINTMENTS_CANCEL: "appointments.cancel",
  APPOINTMENTS_MANAGE: "appointments.manage_availability",

  // AI Agents
  AGENTS_READ: "agents.read",
  AGENTS_CREATE: "agents.create",
  AGENTS_UPDATE: "agents.update",
  AGENTS_PUBLISH: "agents.publish",
  AGENTS_DELETE: "agents.delete",

  // Workflows
  WORKFLOWS_READ: "workflows.read",
  WORKFLOWS_CREATE: "workflows.create",
  WORKFLOWS_UPDATE: "workflows.update",
  WORKFLOWS_PUBLISH: "workflows.publish",
  WORKFLOWS_DELETE: "workflows.delete",

  // Campaigns
  CAMPAIGNS_READ: "campaigns.read",
  CAMPAIGNS_CREATE: "campaigns.create",
  CAMPAIGNS_UPDATE: "campaigns.update",
  CAMPAIGNS_LAUNCH: "campaigns.launch",
  CAMPAIGNS_DELETE: "campaigns.delete",

  // Knowledge Base
  KNOWLEDGE_READ: "knowledge.read",
  KNOWLEDGE_CREATE: "knowledge.create",
  KNOWLEDGE_UPDATE: "knowledge.update",
  KNOWLEDGE_DELETE: "knowledge.delete",

  // Integrations & Social
  INTEGRATIONS_READ: "integrations.read",
  INTEGRATIONS_CONNECT: "integrations.connect",
  INTEGRATIONS_DISCONNECT: "integrations.disconnect",

  // Approvals & Governance
  APPROVALS_READ: "approvals.read",
  APPROVALS_CREATE: "approvals.create",
  APPROVALS_APPROVE: "approvals.approve",
  APPROVALS_REJECT: "approvals.reject",

  // Billing & Subscriptions
  BILLING_READ: "billing.read",
  BILLING_MANAGE: "billing.manage",

  // Workspace & Membership Management
  WORKSPACE_READ: "workspace.read",
  WORKSPACE_UPDATE: "workspace.update",
  WORKSPACE_MANAGE_MEMBERS: "workspace.manage_members",
  WORKSPACE_MANAGE_ROLES: "workspace.manage_roles",
  WORKSPACE_DELETE: "workspace.delete",
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: ALL_PERMISSIONS,
  [ROLES.ADMIN]: ALL_PERMISSIONS.filter((p) => p !== PERMISSIONS.WORKSPACE_DELETE),
  [ROLES.MANAGER]: [
    PERMISSIONS.CONTACTS_READ, PERMISSIONS.CONTACTS_CREATE, PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.COMPANIES_READ, PERMISSIONS.COMPANIES_CREATE, PERMISSIONS.COMPANIES_UPDATE,
    PERMISSIONS.DEALS_READ, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE,
    PERMISSIONS.TASKS_READ, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_UPDATE, PERMISSIONS.TASKS_DELETE,
    PERMISSIONS.CONVERSATIONS_READ, PERMISSIONS.CONVERSATIONS_REPLY, PERMISSIONS.CONVERSATIONS_ASSIGN, PERMISSIONS.CONVERSATIONS_CLOSE, PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE, PERMISSIONS.APPOINTMENTS_CANCEL, PERMISSIONS.APPOINTMENTS_MANAGE,
    PERMISSIONS.AGENTS_READ, PERMISSIONS.AGENTS_CREATE, PERMISSIONS.AGENTS_UPDATE,
    PERMISSIONS.WORKFLOWS_READ, PERMISSIONS.WORKFLOWS_CREATE, PERMISSIONS.WORKFLOWS_UPDATE,
    PERMISSIONS.CAMPAIGNS_READ, PERMISSIONS.CAMPAIGNS_CREATE, PERMISSIONS.CAMPAIGNS_UPDATE, PERMISSIONS.CAMPAIGNS_LAUNCH,
    PERMISSIONS.KNOWLEDGE_READ, PERMISSIONS.KNOWLEDGE_CREATE, PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.INTEGRATIONS_READ,
    PERMISSIONS.APPROVALS_READ, PERMISSIONS.APPROVALS_CREATE, PERMISSIONS.APPROVALS_APPROVE, PERMISSIONS.APPROVALS_REJECT,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.WORKSPACE_READ,
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.CONTACTS_READ, PERMISSIONS.CONTACTS_CREATE, PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.DEALS_READ, PERMISSIONS.DEALS_CREATE, PERMISSIONS.DEALS_UPDATE,
    PERMISSIONS.TASKS_READ, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.CONVERSATIONS_READ, PERMISSIONS.CONVERSATIONS_REPLY, PERMISSIONS.CONVERSATIONS_CLOSE, PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE, PERMISSIONS.APPOINTMENTS_CANCEL,
    PERMISSIONS.AGENTS_READ,
    PERMISSIONS.WORKFLOWS_READ,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.APPROVALS_READ, PERMISSIONS.APPROVALS_CREATE,
    PERMISSIONS.WORKSPACE_READ,
  ],
  [ROLES.MEMBER]: [
    PERMISSIONS.CONTACTS_READ, PERMISSIONS.CONTACTS_CREATE, PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.DEALS_READ, PERMISSIONS.DEALS_CREATE,
    PERMISSIONS.TASKS_READ, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.CONVERSATIONS_READ, PERMISSIONS.CONVERSATIONS_REPLY, PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.AGENTS_READ,
    PERMISSIONS.WORKFLOWS_READ,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.APPROVALS_READ,
    PERMISSIONS.WORKSPACE_READ,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.AGENTS_READ,
    PERMISSIONS.WORKFLOWS_READ,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.APPROVALS_READ,
    PERMISSIONS.WORKSPACE_READ,
  ],
};

export function hasPermission(role, permission) {
  if (!role) return false;
  const normalizedRole = String(role).toLowerCase();
  const permissions = ROLE_PERMISSIONS[normalizedRole] || [];
  return permissions.includes(permission);
}
